stages:
  download: 
    cmd: src/1_download.sh
    deps:
    - src/1_download.sh
    outs:
    - download/
  unzip_build:
    cmd: src/2_unzip_build.sh
    deps:
    - src/2_unzip_build.sh
    - download/
    outs:
    - data/
