stages:
  download: 
    cmd: src/1_download.sh
    deps:
    - src/1_download.sh
    outs:
    - download/
  unzip:
    cmd: src/2_unzip.sh
    deps:
    - src/2_unzip.sh
    - download/
    outs:
    - raw/    
    - temp/
  build:
    cmd: src/3_build_parquet.sh
    deps:
    - src/3_build_parquet.sh
    - src/sdf2parquet.py
    - raw/
    - temp/
    outs:
    - data/
