stages:
  download_data:
    cmd: Rscript R/downloadCompoundsSDF.R
    deps:
    - R/downloadCompoundsSDF.R
    outs:
    - download/
  unzip_data:
    cmd: Rscript R/gunzipCompoundsSDF.R
    deps:
    - download/
    - R/gunzipCompoundsSDF.R
    outs:
    - raw/
  build_data:
    cmd: python R/buildCompoundsSDF.py
    deps:
    - raw/
    - R/buildCompoundsSDF.py
    outs:
    - data/
