library(purrr)
library(fs)
library(arrow)
library(readr)
library(dplyr)
library(plyr)
library(XML)
library(xml2)
library(methods)
library(R.utils)
library(cinf)

tsub <- \(p,r){partial(gsub,pattern=p,replacement=r,ignore.case=T)}
deps <- dir_ls("download")
out  <- dir_create("raw")
outs <- path(out, path_file(deps)) |> tsub("\\..*", ".sdf")()
fs::dir_ls(out) |> fs::file_delete()
start_time <- Sys.time()
print(start_time)
walk2(deps, outs, ~ gunzip(.x, .y, remove = FALSE))
stop_time <- Sys.time()
print(stop_time)
print(stop_time - start_time)